import { readFileSync, readdirSync, statSync, existsSync } from 'fs';
import { resolve } from 'path';
import { describe, expect, it } from 'vitest';

// The kitchen Pi has no system emoji font, so event titles like "🚖 Eleanor"
// rendered as tofu boxes on the wall while looking fine on a Mac. We ship our
// own colour face for it (styles/fonts.css, generated by scripts/fetch-emoji-font.mjs).
//
// Every assertion here guards a failure that is INVISIBLE from a dev machine —
// a Mac has Apple Color Emoji, which papers over a broken font stack. Only the
// wall would tell you, days later.

const root = resolve(__dirname, '..');
const read = (p: string) => readFileSync(resolve(root, p), 'utf8');
const fontsCss = read('styles/fonts.css');

type Face = { file: string; ranges: Array<[number, number]> };

const faces: Face[] = [...fontsCss.matchAll(/@font-face\s*{([^}]+)}/g)].map((m) => {
  const body = m[1];
  const file = body.match(/url\('([^']+)'\)/)![1];
  const raw = body.match(/unicode-range:\s*([^;]+);/)![1];
  const ranges = [...raw.matchAll(/U\+([0-9A-Fa-f]+)(?:-([0-9A-Fa-f]+))?/g)].map(
    (r) => [parseInt(r[1], 16), parseInt(r[2] ?? r[1], 16)] as [number, number]
  );
  return { file, ranges };
});

/** Does any vendored slice claim this codepoint? */
const claims = (cp: number) => faces.some((f) => f.ranges.some(([lo, hi]) => cp >= lo && cp <= hi));

describe('emoji font is wired up', () => {
  it('vendors every slice the stylesheet points at', () => {
    expect(faces.length).toBeGreaterThanOrEqual(8);
    for (const f of faces) {
      const onDisk = resolve(root, 'public', f.file.replace(/^\//, ''));
      expect(existsSync(onDisk), `${f.file} is referenced but missing`).toBe(true);
      expect(statSync(onDisk).size).toBeGreaterThan(5_000);
    }
  });

  it('is imported into the global stylesheet', () => {
    expect(read('app/globals.css')).toContain("@import '../styles/fonts.css';");
  });

  it('covers the emoji the family actually uses in titles', () => {
    expect(claims(0x1f696)).toBe(true); // 🚖 oncoming taxi — the pickup/dropoff template
    expect(claims(0x1f695)).toBe(true); // 🚕 taxi
    expect(claims(0xfe0f)).toBe(true); // variation selector-16
    expect(claims(0x200d)).toBe(true); // zero-width joiner
  });
});

// THE ORDERING IS LOAD-BEARING, NOT COSMETIC.
//
// Google's subsets include the keycap bases — U+23 (#), U+2A (*) and U+30-39
// (the DIGITS) — so that 1️⃣ can be composed. Our face therefore claims the
// digits outright. It only stays harmless because Inter sits ahead of it in the
// body stack and wins every codepoint it can supply.
//
// Move 'HomeHQ Emoji' before Inter and every digit on the wall — the clock, all
// event times — becomes a keycap emoji.
describe('the emoji font can only supply glyphs Inter lacks', () => {
  it('claims the keycap digits, so ordering has to protect them', () => {
    expect(claims(0x30)).toBe(true); // '0' — yes, really
    expect(claims(0x23)).toBe(true); // '#'
  });

  it('sits AFTER Inter in the body font stack', () => {
    const base = read('styles/base.css');
    const stack = base.match(/font-family:\s*([^;]+);/)![1];
    expect(stack).toMatch(/var\(--font-inter\)\s*,\s*'HomeHQ Emoji'/);
    expect(stack.indexOf('--font-inter')).toBeLessThan(stack.indexOf('HomeHQ Emoji'));
  });

  it('never claims the punctuation and symbols the UI draws itself', () => {
    // These fall outside Inter's `latin` subset, so if our face claimed them it
    // would win — silently restyling the chrome. (✕ is the footer's "Show all"
    // and the calendar picker's token remove button.)
    const chrome = '✕▾●│↻⌘‹›–…•→≥≤';
    const stolen = [...chrome].filter((ch) => claims(ch.codePointAt(0)!));
    expect(stolen).toEqual([]);
  });
});

describe('no UI chrome character collides with the emoji font', () => {
  const sources: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(resolve(root, dir))) {
      const rel = `${dir}/${name}`;
      if (statSync(resolve(root, rel)).isDirectory()) walk(rel);
      else if (/\.(tsx|css)$/.test(name)) sources.push(rel);
    }
  };
  walk('components');
  walk('app');

  it('every non-ASCII character the UI draws stays with Inter or the system font', () => {
    const offenders = new Map<string, string>();
    for (const rel of sources) {
      for (const ch of read(rel)) {
        const cp = ch.codePointAt(0)!;
        if (cp > 0x2000 && claims(cp)) offenders.set(ch, rel);
      }
    }
    expect(
      [...offenders].map(([ch, w]) => `${ch} (U+${ch.codePointAt(0)!.toString(16)}) in ${w}`)
    ).toEqual([]);
  });
});

// The font path must stay OUT of the auth gate. It isn't covered by the
// _next/static exclusion (that only covers Next's own build output), and
// next.config stamps /fonts/* with a one-year `public, immutable` header — so
// while it was gated, that header landed on the 307 redirect to /login and
// Cloudflare cached the REDIRECT at the edge, serving it even to the
// authenticated kiosk. The wall showed tofu with a perfectly good font shipped.
//
// This is invisible locally: DEV_AUTH_BYPASS returns before the matcher runs.
describe('the font path is not behind the auth gate', () => {
  const matcher = read('proxy.ts').match(/matcher:\s*\['([^']+)'\]/)![1];
  const re = new RegExp(`^${matcher.replace(/\\\\/g, '\\')}$`);

  it('the proxy matcher skips /fonts/*', () => {
    for (const f of faces) expect(re.test(f.file), `${f.file} is gated`).toBe(false);
    expect(re.test('/fonts/emoji/anything.woff2')).toBe(false);
  });

  it('still gates the app itself', () => {
    for (const p of ['/', '/api/calendar', '/setup']) {
      expect(re.test(p), `${p} must stay gated`).toBe(true);
    }
  });
});

describe('font filenames are content-hashed', () => {
  it('every slice URL carries a hash, so `immutable` is honest', () => {
    for (const f of faces) {
      expect(f.file, `${f.file} has no content hash`).toMatch(/\.[0-9a-f]{8}\.woff2$/);
    }
  });
});
